/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

// assets
import model from '../../../assets/models3d/character.glb';

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.SkinnedMesh
    spine: THREE.Bone
    root: THREE.Bone
    ['MCH-torsoparent']: THREE.Bone
    ['MCH-hand_ikparentL']: THREE.Bone
    ['MCH-upper_arm_ik_targetparentL']: THREE.Bone
    ['MCH-hand_ikparentR']: THREE.Bone
    ['MCH-upper_arm_ik_targetparentR']: THREE.Bone
    ['MCH-foot_ikparentL']: THREE.Bone
    ['MCH-thigh_ik_targetparentL']: THREE.Bone
    ['MCH-foot_ikparentR']: THREE.Bone
    ['MCH-thigh_ik_targetparentR']: THREE.Bone
  }
  materials: {}
}

export default function Character(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes } = useGLTF(model) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig" rotation={[Math.PI, 0, Math.PI]} scale={5.79}>
          <primitive object={nodes.spine} />
        </group>
        <group name="rig" rotation={[Math.PI, 0, Math.PI]} scale={5.79}>
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} skeleton={nodes.Cube.skeleton} />
        </group>
        <group name="WGT-rig_spine_fk" position={[0, 1.16, -0.02]} rotation={[1.82, 0, 0]} scale={0.15} />
        <group name="WGT-rig_spine_fk001" position={[0, 1.29, 0]} rotation={[1.69, 0, 0]} scale={0.14} />
        <group name="WGT-rig_spine_fk002" position={[0, 1.29, 0]} rotation={[1.54, 0, 0]} scale={0.17} />
        <group name="WGT-rig_spine_fk003" position={[0, 1.47, -0.01]} rotation={[1.54, 0, 0]} scale={0.19} />
        <group name="WGT-rig_tweak_spine" position={[0, 1.01, -0.06]} rotation={[1.82, 0, 0]} scale={0.08} />
        <group name="WGT-rig_tweak_spine001" position={[0, 1.16, -0.02]} rotation={[1.69, 0, 0]} scale={0.07} />
        <group name="WGT-rig_tweak_spine002" position={[0, 1.29, 0]} rotation={[1.54, 0, 0]} scale={0.09} />
        <group name="WGT-rig_tweak_spine003" position={[0, 1.47, -0.01]} rotation={[1.54, 0, 0]} scale={0.1} />
        <group name="WGT-rig_tweak_spine004" position={[0, 1.66, -0.01]} rotation={[1.63, 0, 0]} scale={0.03} />
        <group name="WGT-rig_torso" position={[0, 1.08, -0.04]} scale={0.39} />
        <group name="WGT-rig_hips" position={[0, 1.01, -0.06]} rotation={[1.82, 0, 0]} scale={0.16} />
        <group name="WGT-rig_chest" position={[0, 1.47, -0.01]} rotation={[1.54, 0, 0]} scale={0.22} />
        <group name="WGT-rig_breastL" position={[0.1, 1.51, -0.05]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.14} />
        <group name="WGT-rig_breastR" position={[-0.1, 1.51, -0.05]} rotation={[0, 0, Math.PI]} scale={-0.14} />
        <group name="WGT-rig_shoulderL" position={[0.04, 1.65, 0]} rotation={[-0.96, -1.31, -0.87]} scale={0.15} />
        <group name="WGT-rig_upper_arm_parentL" position={[0.2, 1.61, 0]} rotation={[-1.49, -0.53, 3.06]} scale={0.09} />
        <group name="WGT-rig_upper_arm_fkL" position={[0.2, 1.61, 0]} rotation={[-1.49, -0.53, 3.06]} scale={0.35} />
        <group name="WGT-rig_forearm_fkL" position={[0.38, 1.31, -0.03]} rotation={[-1.67, -0.51, 2.97]} scale={0.41} />
        <group name="WGT-rig_hand_fkL" position={[0.58, 0.95, 0.01]} rotation={[-1.69, -0.43, 2.96]} scale={0.09} />
        <group name="WGT-rig_upper_arm_ikL" position={[0.2, 1.61, 0]} rotation={[-1.49, -0.53, 3.06]} scale={0.35} />
        <group name="WGT-rig_upper_arm_ik_targetL" position={[0.46, 1.34, -0.78]} rotation={[-3.09, 0.11, 2.27]} scale={0.09} />
        <group name="WGT-rig_hand_ikL" position={[0.58, 0.95, 0.01]} rotation={[-1.69, -0.43, 2.96]} scale={0.09} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleL" position={[0.38, 1.31, -0.03]} rotation={[Math.PI / 2, 0, -2.75]} scale={0.76} />
        <group name="WGT-rig_upper_arm_tweakL" position={[0.2, 1.61, 0]} rotation={[-1.49, -0.53, 3.06]} scale={0.09} />
        <group name="WGT-rig_upper_arm_tweakL001" position={[0.29, 1.46, -0.01]} rotation={[-1.49, -0.53, 3.06]} scale={0.09} />
        <group name="WGT-rig_forearm_tweakL" position={[0.38, 1.31, -0.03]} rotation={[-1.67, -0.51, 2.97]} scale={0.1} />
        <group name="WGT-rig_forearm_tweakL001" position={[0.48, 1.13, -0.01]} rotation={[-1.67, -0.51, 2.97]} scale={0.1} />
        <group name="WGT-rig_hand_tweakL" position={[0.58, 0.95, 0.01]} rotation={[-1.69, -0.43, 2.96]} scale={0.02} />
        <group name="WGT-rig_shoulderR" position={[-0.04, 1.65, 0]} rotation={[2.18, -1.31, -0.87]} scale={-0.15} />
        <group name="WGT-rig_upper_arm_parentR" position={[-0.2, 1.61, 0]} rotation={[1.65, -0.53, 3.06]} scale={-0.09} />
        <group name="WGT-rig_upper_arm_fkR" position={[-0.2, 1.61, 0]} rotation={[1.65, -0.53, 3.06]} scale={-0.35} />
        <group name="WGT-rig_forearm_fkR" position={[-0.38, 1.31, -0.03]} rotation={[1.47, -0.51, 2.97]} scale={-0.41} />
        <group name="WGT-rig_hand_fkR" position={[-0.58, 0.95, 0.01]} rotation={[1.46, -0.43, 2.96]} scale={-0.09} />
        <group name="WGT-rig_upper_arm_ikR" position={[-0.2, 1.61, 0]} rotation={[1.65, -0.53, 3.06]} scale={-0.35} />
        <group name="WGT-rig_upper_arm_ik_targetR" position={[-0.46, 1.34, -0.78]} rotation={[0.05, 0.11, 2.27]} scale={-0.09} />
        <group name="WGT-rig_hand_ikR" position={[-0.58, 0.95, 0.01]} rotation={[1.46, -0.43, 2.96]} scale={-0.09} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleR" position={[-0.38, 1.31, -0.03]} rotation={[-Math.PI / 2, 0, -2.75]} scale={-0.76} />
        <group name="WGT-rig_upper_arm_tweakR" position={[-0.2, 1.61, 0]} rotation={[1.65, -0.53, 3.06]} scale={-0.09} />
        <group name="WGT-rig_upper_arm_tweakR001" position={[-0.29, 1.46, -0.01]} rotation={[1.65, -0.53, 3.06]} scale={-0.09} />
        <group name="WGT-rig_forearm_tweakR" position={[-0.38, 1.31, -0.03]} rotation={[1.47, -0.51, 2.97]} scale={-0.1} />
        <group name="WGT-rig_forearm_tweakR001" position={[-0.48, 1.13, -0.01]} rotation={[1.47, -0.51, 2.97]} scale={-0.1} />
        <group name="WGT-rig_hand_tweakR" position={[-0.58, 0.95, 0.01]} rotation={[1.46, -0.43, 2.96]} scale={-0.02} />
        <group name="WGT-rig_neck" position={[0, 1.66, -0.01]} rotation={[1.6, 0, 0]} scale={0.12} />
        <group name="WGT-rig_head" position={[0, 1.78, -0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.2} />
        <group name="WGT-rig_tweak_spine005" position={[0, 1.72, -0.01]} rotation={[1.57, 0, 0]} scale={0.03} />
        <group name="WGT-rig_thigh_parentL" position={[0.13, 1.07, -0.01]} rotation={[-1.62, -0.1, 0.62]} scale={0.11} />
        <group name="WGT-rig_thigh_fkL" position={[0.13, 1.07, -0.01]} rotation={[-1.62, -0.1, 0.62]} scale={0.44} />
        <group name="WGT-rig_shin_fkL" position={[0.18, 0.63, 0.01]} rotation={[-1.54, -0.04, 0.62]} scale={0.55} />
        <group name="WGT-rig_foot_fkL" position={[0.2, 0.08, -0.01]} rotation={[-2.67, 0, 0]} scale={0.12} />
        <group name="WGT-rig_toe_fkL" position={[0.2, 0.03, 0.09]} rotation={[-3.06, 0, Math.PI]} scale={0.07} />
        <group name="WGT-rig_thigh_ikL" position={[0.13, 1.07, -0.01]} rotation={[-1.62, -0.1, 0.62]} scale={0.44} />
        <group name="WGT-rig_thigh_ik_targetL" position={[0.75, 0.68, 0.82]} rotation={[-0.05, 0.62, 0.02]} scale={0.12} />
        <group name="WGT-rig_foot_ikL" position={[0.2, 0.08, -0.01]} scale={0.12} />
        <group name="WGT-rig_VIS_thigh_ik_poleL" position={[0.18, 0.63, 0.01]} rotation={[Math.PI / 2, 0, 0.66]} scale={0.99} />
        <group name="WGT-rig_thigh_tweakL" position={[0.13, 1.07, -0.01]} rotation={[-1.62, -0.1, 0.62]} scale={0.11} />
        <group name="WGT-rig_thigh_tweakL001" position={[0.16, 0.85, 0]} rotation={[-1.62, -0.1, 0.62]} scale={0.11} />
        <group name="WGT-rig_shin_tweakL" position={[0.18, 0.63, 0.01]} rotation={[-1.54, -0.04, 0.62]} scale={0.14} />
        <group name="WGT-rig_shin_tweakL001" position={[0.19, 0.36, 0]} rotation={[-1.54, -0.04, 0.62]} scale={0.14} />
        <group name="WGT-rig_foot_tweakL" position={[0.2, 0.08, -0.01]} rotation={[-2.67, 0, 0]} scale={0.03} />
        <group name="WGT-rig_foot_spin_ikL" position={[0.2, 0.03, 0.09]} scale={0.06} />
        <group name="WGT-rig_foot_heel_ikL" position={[0.2, 0.08, -0.01]} scale={0.06} />
        <group name="WGT-rig_toe_ikL" position={[0.2, 0.03, 0.09]} rotation={[-3.06, 0, Math.PI]} scale={0.07} />
        <group name="WGT-rig_thigh_parentR" position={[-0.13, 1.07, -0.01]} rotation={[1.52, -0.1, 0.62]} scale={-0.11} />
        <group name="WGT-rig_thigh_fkR" position={[-0.13, 1.07, -0.01]} rotation={[1.52, -0.1, 0.62]} scale={-0.44} />
        <group name="WGT-rig_shin_fkR" position={[-0.18, 0.63, 0.01]} rotation={[1.61, -0.04, 0.62]} scale={-0.55} />
        <group name="WGT-rig_foot_fkR" position={[-0.2, 0.08, -0.01]} rotation={[0.47, 0, 0]} scale={-0.12} />
        <group name="WGT-rig_toe_fkR" position={[-0.2, 0.03, 0.09]} rotation={[0.08, 0, -Math.PI]} scale={-0.07} />
        <group name="WGT-rig_thigh_ikR" position={[-0.13, 1.07, -0.01]} rotation={[1.52, -0.1, 0.62]} scale={-0.44} />
        <group name="WGT-rig_thigh_ik_targetR" position={[-0.75, 0.68, 0.82]} rotation={[3.09, 0.62, 0.02]} scale={-0.12} />
        <group name="WGT-rig_foot_ikR" position={[-0.2, 0.08, -0.01]} rotation={[-Math.PI, 0, 0]} scale={-0.12} />
        <group name="WGT-rig_VIS_thigh_ik_poleR" position={[-0.18, 0.63, 0.01]} rotation={[-Math.PI / 2, 0, 0.66]} scale={-0.99} />
        <group name="WGT-rig_thigh_tweakR" position={[-0.13, 1.07, -0.01]} rotation={[1.52, -0.1, 0.62]} scale={-0.11} />
        <group name="WGT-rig_thigh_tweakR001" position={[-0.16, 0.85, 0]} rotation={[1.52, -0.1, 0.62]} scale={-0.11} />
        <group name="WGT-rig_shin_tweakR" position={[-0.18, 0.63, 0.01]} rotation={[1.61, -0.04, 0.62]} scale={-0.14} />
        <group name="WGT-rig_shin_tweakR001" position={[-0.19, 0.36, 0]} rotation={[1.61, -0.04, 0.62]} scale={-0.14} />
        <group name="WGT-rig_foot_tweakR" position={[-0.2, 0.08, -0.01]} rotation={[0.47, 0, 0]} scale={-0.03} />
        <group name="WGT-rig_foot_spin_ikR" position={[-0.2, 0.03, 0.09]} rotation={[-Math.PI, 0, 0]} scale={-0.06} />
        <group name="WGT-rig_foot_heel_ikR" position={[-0.2, 0.08, -0.01]} rotation={[-Math.PI, 0, 0]} scale={-0.06} />
        <group name="WGT-rig_toe_ikR" position={[-0.2, 0.03, 0.09]} rotation={[0.08, 0, -Math.PI]} scale={-0.07} />
        <group name="WGT-rig_root" scale={0.93} />
      </group>
    </group>
  )
}

useGLTF.preload(model)
